kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: play-bolt
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: play-bolt
    spec:
      containers:
        - name: play-bolt
          image: play-bolt:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: SLACK_BOT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: play-bolt
                  key: SLACK_BOT_TOKEN
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: play-bolt
                  key: SLACK_SIGNING_SECRET
          ports:
            - containerPort: 13000
---
apiVersion: v1
kind: Service
metadata:
  name: play-bolt
spec:
  type: NodePort
  selector:
    app: play-bolt
  ports:
    - protocol: TCP
      port: 13000
